<?php

/**
 * BaseWord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $wordlist_id
 * @property Wordlist $Wordlist
 * 
 * @method integer  getWordlistId()  Returns the current record's "wordlist_id" value
 * @method Wordlist getWordlist()    Returns the current record's "Wordlist" value
 * @method Word     setWordlistId()  Sets the current record's "wordlist_id" value
 * @method Word     setWordlist()    Sets the current record's "Wordlist" value
 * 
 * @package    greight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWord extends sfWordnikWord
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('word');
        $this->hasColumn('wordlist_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Wordlist', array(
             'local' => 'wordlist_id',
             'foreign' => 'id'));
    }
}