<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/05/05 23:02:19

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=greight',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
