<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/05/16 15:35:56

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=greight',
  'username' => 'root',
  'password' => 'Evoleye-Mac',
  'name' => 'doctrine',
)),);
