<?php

/**
 * PluginsfWordnikWord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsfWordnikWord extends BasesfWordnikWord
{
	public function populate($json) {
		$wordObj = json_decode($json);
		$this->name = $wordObj->headword;
		foreach($wordObj->definitions as $definition) {
			$this->Definitions[]->text = $definition;
		}
		foreach($wordObj->examples as $example) {
			$this->Examples[]->text = $example;
		}
		foreach($wordObj->related as $related) {
			$this->RelatedWords[]->text = $related;
		}
	}
}