<?php

/**
 * PluginsfWordnikRelatedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfWordnikRelatedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfWordnikRelatedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfWordnikRelated');
    }
}