<?php

/**
 * PluginsfWordnikDefinitionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfWordnikDefinitionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfWordnikDefinitionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfWordnikDefinition');
    }
}