<?php

/**
 * PluginsfWordnikRelatedWordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfWordnikRelatedWordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfWordnikRelatedWordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfWordnikRelatedWord');
    }
}