<?php

/**
 * PluginsfWordnikWordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfWordnikWordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfWordnikWordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfWordnikWord');
    }
}