<?php

/**
 * PluginsfWordnikExampleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfWordnikExampleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfWordnikExampleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfWordnikExample');
    }
}