<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2010/05/08 12:32:35
return array(

  // sfWordnikPlugin_module_libs

  // sfWordnikPlugin_lib
  'wordnik' => '/Users/jmw/Sites/greight/plugins/sfWordnikPlugin/lib/Wordnik/Wordnik.php',

  // sfPicasaPlugin_module_libs

  // sfPicasaPlugin_lib
  'picasa_account' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Account.php',
  'picasa_album' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Album.php',
  'picasa_author' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Author.php',
  'picasa_cache' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Cache.php',
  'picasa_comment' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Comment.php',
  'picasa_exception_badrequestexception' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Exception/BadRequestException.php',
  'picasa_exception_captcharequiredexception' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Exception/CaptchaRequiredException.php',
  'picasa_exception_conflictexception' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Exception/ConflictException.php',
  'picasa_exception_failedauthorizationexception' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Exception/FailedAuthorizationException.php',
  'picasa_exception_filenotfoundexception' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Exception/FileNotFoundException.php',
  'picasa_exception_internalservererrorexception' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Exception/InternalServerErrorException.php',
  'picasa_exception_invalidusernameorpasswordexception' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Exception/InvalidUsernameOrPasswordException.php',
  'picasa_exception_unauthorizedexception' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Exception/UnauthorizedException.php',
  'picasa_exception' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Exception.php',
  'picasa_image' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Image.php',
  'picasa_imagecollection' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/ImageCollection.php',
  'picasa_logger' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Logger.php',
  'picasa_tag' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Tag.php',
  'picasa_thumbnail' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa/Thumbnail.php',
  'picasa' => '/Users/jmw/Sites/greight/plugins/sfPicasaPlugin/lib/Picasa.php',

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => '/Users/jmw/Sites/greight/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'basewordformfilter' => '/Users/jmw/Sites/greight/lib/filter/doctrine/base/BaseWordFormFilter.class.php',
  'baseformfilterdoctrine' => '/Users/jmw/Sites/greight/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'wordformfilter' => '/Users/jmw/Sites/greight/lib/filter/doctrine/WordFormFilter.class.php',
  'baseform' => '/Users/jmw/Sites/greight/lib/form/BaseForm.class.php',
  'basewordform' => '/Users/jmw/Sites/greight/lib/form/doctrine/base/BaseWordForm.class.php',
  'baseformdoctrine' => '/Users/jmw/Sites/greight/lib/form/doctrine/BaseFormDoctrine.class.php',
  'wordform' => '/Users/jmw/Sites/greight/lib/form/doctrine/WordForm.class.php',

  // project_model
  'baseword' => '/Users/jmw/Sites/greight/lib/model/doctrine/base/BaseWord.class.php',
  'word' => '/Users/jmw/Sites/greight/lib/model/doctrine/Word.class.php',
  'wordtable' => '/Users/jmw/Sites/greight/lib/model/doctrine/WordTable.class.php',

  // application
  'myuser' => '/Users/jmw/Sites/greight/apps/frontend/lib/myUser.class.php',

  // modules
);
