<?php

/**
 * BasesfWordnikWord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Definitions
 * @property Doctrine_Collection $Examples
 * @property Doctrine_Collection $RelatedWords
 * @property Profile $Profile
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method Doctrine_Collection getDefinitions()  Returns the current record's "Definitions" collection
 * @method Doctrine_Collection getExamples()     Returns the current record's "Examples" collection
 * @method Doctrine_Collection getRelatedWords() Returns the current record's "RelatedWords" collection
 * @method Profile             getProfile()      Returns the current record's "Profile" value
 * @method sfWordnikWord       setId()           Sets the current record's "id" value
 * @method sfWordnikWord       setName()         Sets the current record's "name" value
 * @method sfWordnikWord       setDefinitions()  Sets the current record's "Definitions" collection
 * @method sfWordnikWord       setExamples()     Sets the current record's "Examples" collection
 * @method sfWordnikWord       setRelatedWords() Sets the current record's "RelatedWords" collection
 * @method sfWordnikWord       setProfile()      Sets the current record's "Profile" value
 * 
 * @package    greight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfWordnikWord extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_wordnik_word');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfWordnikDefinition as Definitions', array(
             'local' => 'id',
             'foreign' => 'sf_wordnik_word_id'));

        $this->hasMany('sfWordnikExample as Examples', array(
             'local' => 'id',
             'foreign' => 'sf_wordnik_word_id'));

        $this->hasMany('sfWordnikRelatedWord as RelatedWords', array(
             'local' => 'id',
             'foreign' => 'sf_wordnik_word_id'));

        $this->hasOne('Profile', array(
             'local' => 'id',
             'foreign' => 'favorite_word_id'));
    }
}