<?php

/**
 * BasesfWordnikRelated
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $sf_wordnik_word_id
 * @property string $text
 * @property sfWordnikWord $Related
 * 
 * @method integer          getId()                 Returns the current record's "id" value
 * @method integer          getSfWordnikWordId()    Returns the current record's "sf_wordnik_word_id" value
 * @method string           getText()               Returns the current record's "text" value
 * @method sfWordnikWord    getRelated()            Returns the current record's "Related" value
 * @method sfWordnikRelated setId()                 Sets the current record's "id" value
 * @method sfWordnikRelated setSfWordnikWordId()    Sets the current record's "sf_wordnik_word_id" value
 * @method sfWordnikRelated setText()               Sets the current record's "text" value
 * @method sfWordnikRelated setRelated()            Sets the current record's "Related" value
 * 
 * @package    greight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfWordnikRelated extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_wordnik_related');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('sf_wordnik_word_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('text', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfWordnikWord as Related', array(
             'local' => 'sf_wordnik_word_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}